import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import ThemeProvider from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Nithish's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class" // This allows Tailwind to toggle the class on <html>
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider className="w-full">
            <AppSidebar />
            <div className="flex mt-10">
              <main className="flex-1">{children}</main>
            </div>
            <SidebarTrigger />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
